server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: api-gateway

apihub:
  jwt:
    secret: ApiHubCourseDesignSecretKeyMustBeLongEnough2026
    expire-seconds: 7200
  routes:
    auth: http://127.0.0.1:8081
    admin: http://127.0.0.1:8082
    invoke: http://127.0.0.1:8083

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%X{traceId}] %-5level %logger{36} - %msg%n"
