server:
  port: 8083

spring:
  application:
    name: api-invoke

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%X{traceId}] %-5level %logger{36} - %msg%n"
